name: credit_note
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.2
  isar_flutter_libs: ^3.1.0+1
  http: ^1.2.2
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  google_fonts: ^6.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

  flutter_localizations:
    sdk: flutter
  drag_and_drop_lists: ^0.4.1
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.1.0
  flutter_hooks: ^0.20.5
  charset_converter: ^2.2.0
  external_path: ^2.0.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.0
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Light.ttf
        - asset: assets/fonts/KiwiMaru-Medium.ttf
        - asset: assets/fonts/KiwiMaru-Regular.ttf

flutter_native_splash:
  image: "assets/images/credit_note_background.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
